// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Egide.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorWindow : FancyWindow
{
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    private const string DiscordUrl = "https://discord.gg/dP3nnKYzdF";

    public SponsorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SyndicateBuyButton.OnPressed += OnBuyPressed;
        ShabolovkaBuyButton.OnPressed += OnBuyPressed;
        LegendBuyButton.OnPressed += OnBuyPressed;
    }

    private void OnBuyPressed(BaseButton.ButtonEventArgs args)
    {
        _uriOpener.OpenUri(DiscordUrl);
    }
}
